#!/bin/bash

OPTIONS="Lock\nLogout\nShutdown"
SELECTION=$(echo -e $OPTIONS | rofi -dmenu -i -p "λ System Power Options::" -font "Source Code Pro 12" -fg '#d28b71' -hlbg '#f4bc87'  )

case $SELECTION in
     "Lock") i3lock -i ~/Pictures/Wallpapers/abstract5.png && sleep 1 ;;
     "Logout") i3-msg exit ;;
     "Shutdown") cinnamon-session-quit --power-off ;;
esac
