#!/bin/bash

# if no interface is found, use the first device with a global scope
INTERFACE="${BLOCK_INSTANCE:-wlan0}"
IPADDR=$(ip route get 1 | awk '{print $NF;exit}')
# get external ip from duch website
WANIP=$(curl -s http://whatismijnip.nl |cut -d " " -f 5)
SSID=$(iwgetid $INTERFACE -r)
QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')


# if the machine has no battery or wireless connection, the corresponding block should display error.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && echo "<span foreground='#969896'>/</span><span font='10' rise='-1500' foreground='#B294BB'>  </span><span foreground='#969896'>/</span><span foreground='#282A2E'>|</span>"


  if [[ $QUALITY -ge 80 ]]; then
      echo "<span foreground='#7bbda4'></span><span foreground='#282A2E'>|</span>"
  elif [[ $QUALITY -lt 80 ]]; then
      echo "<span foreground='#f4bc87'></span><span foreground='#282A2E'>|</span>"
  elif [[ $QUALITY -lt 60 ]]; then
      echo "<span foreground='#bd28b71'></span><span foreground='#282A2E'>|</span>" #orange
  elif [[ $QUALITY -lt 40 ]]; then
      echo "<span foreground='#cb6077'></span><span foreground='#282A2E'>|</span>" #red
fi

# mouse buttons
case $BLOCK_BUTTON in
    1) rofi-connm ;; # rofi connection manager
esac
