#!/bin/sh

dt0=$(date '+%a')
dt1=$(date '+%d')
dt2=$(date '+%b')
dt3=$(date '+%H')
dt4=$(date '+%M')

echo "<span foreground='#7bbda4'> </span>$dt0 $dt1 $dt2 $dt3<span foreground='#969896'>:</span>$dt4"

case $BLOCK_BUTTON in
    1) i3-msg exec gsimplecal ;; #left click calendar
    3) i3-msg exec "firefox https://calendar.google.com" ;; #right click,google calendar
esac
