#!/bin/bash

# toggles the external monitor on/off in specified direction
# Hard coding the resolutions for my work monitor and seeing about setting some scaling
# details so I can have UHD when in single screen mode
IN="eDP1"
EXT="DP1"
DIRECTION="right"

if (xrandr | grep "$EXT disconnected"); then
    xrandr --output $IN --mode 1920x1080 --output $EXT --off 
else
    xrandr --output $IN --mode 1920x1080 --primary --output $EXT --mode 1920x1080 --$DIRECTION-of $IN
fi
