#! /bin/bash
# Enumerate the columns of a csv :: default to using comma as the separator

usage() {
    echo "coln :: Enumerate the columns of a csv"
    echo "--------------------------------------"
    echo ""
    echo "  -d  set the field deliminator. (default: ',')"
    echo "  -h  display this help message"
    echo ""
}

DELIM=","
SHOW_NUMS=true

while getopts ':hd:' opt; do
    case "${opt}" in
        d)
            DELIM="${OPTARG}" ;;
        h | *)
            usage
            exit 0 ;;
    esac
done
shift $((OPTIND-1))

FILE=$1

if [ "$FILE" = "" ]; then
    usage
    exit 1
fi

head -n 1 $FILE | tr ${DELIM} '\n' | nl
